data "aws_region" "current" {}
resource "aws_cognito_user_pool" "derbyUserPool" {
  name = "derbyUserPool"
  email_verification_subject="User Verification for ${var.DeployEnvironment}"
auto_verified_attributes=["email"]
  schema {
    attribute_data_type = "String"
    name                = "email"

          developer_only_attribute = false
          mutable                  = false 
          required                 = false

          string_attribute_constraints {
              max_length = "2048" 
              min_length = "0" 
            }
  }
}
resource "aws_cognito_user_pool_client" "sveltePoolClient" {
  name = "sveltePoolClient"

  user_pool_id = aws_cognito_user_pool.derbyUserPool.id
}
resource "aws_cognito_user_pool_client" "idpLink" {
  name = "ipdLink"

  user_pool_id = aws_cognito_user_pool.derbyUserPool.id
}
resource "aws_cognito_identity_pool" "derbyMainIdp" {
  identity_pool_name               = "derbyMainIdp"
  allow_unauthenticated_identities = false

  cognito_identity_providers {
    client_id               = aws_cognito_user_pool_client.idpLink.id
    provider_name           = aws_cognito_user_pool.derbyUserPool.endpoint
    server_side_token_check = false
  }
  cognito_identity_providers {
    client_id               = aws_cognito_user_pool_client.sveltePoolClient.id
    provider_name           = aws_cognito_user_pool.derbyUserPool.endpoint
    server_side_token_check = false
  }
}
locals {
	awsCognitoSettingsJson= jsonencode({
    "aws_project_region"= "${data.aws_region.current.name}",
    "aws_cognito_identity_pool_id"= "${aws_cognito_identity_pool.derbyMainIdp.id}",
    "aws_cognito_region"= "${data.aws_region.current.name}",
    "aws_user_pools_id"= "${aws_cognito_user_pool.derbyUserPool.id}",
    "aws_user_pools_web_client_id"= "${aws_cognito_user_pool_client.sveltePoolClient.id}",
    "aws_pubsub_region"= "${data.aws_region.current.name}",
    "aws_pubsub_endpoint"= "wss://${data.aws_iot_endpoint.mqtt.endpoint_address}/mqtt",
    "oauth"= {}
	})

}

resource "local_file" "migrateToAjax" {
    content     = <<-EOT
// WARNING: DO NOT EDIT. This file is automatically generated by terraform  counterfeitAmplifySettings. It will be overwritten.
const awsmobile = ${local.awsCognitoSettingsJson}

export default awsmobile;
  EOT
    filename = "/tmp/migrate-exports.js"
}


//
//
//

resource "local_file" "counterfeitAmplifySettings" {
    content     = <<-EOT
// WARNING: DO NOT EDIT. This file is automatically generated by terraform  counterfeitAmplifySettings. It will be overwritten.

const awsmobile = {
    "aws_project_region": "${data.aws_region.current.name}",
    "aws_cognito_identity_pool_id": "${aws_cognito_identity_pool.derbyMainIdp.id}",
    "aws_cognito_region": "${data.aws_region.current.name}",
    "aws_user_pools_id": "${aws_cognito_user_pool.derbyUserPool.id}",
    "aws_user_pools_web_client_id": "${aws_cognito_user_pool_client.sveltePoolClient.id}",
    "aws_pubsub_region": "${data.aws_region.current.name}",
    "aws_pubsub_endpoint": "wss://${data.aws_iot_endpoint.mqtt.endpoint_address}/mqtt",
    "oauth": {}
};


export default awsmobile;
  EOT
    filename = "${path.module}/../frontend/src/aws-exports.js"
}

output derbyUserPool {
        value=aws_cognito_user_pool.derbyUserPool
}
output sveltePoolClient {
        value=aws_cognito_user_pool_client.sveltePoolClient
	sensitive = true
}
