# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: zellopa2
provider:
    name: aws
    region: us-east-2
    runtime: nodejs14.x
    memorySize: 128 # optional, in MB, default is 1024
    timeout: 30 # optional, in seconds, default is 6
    environment:
        ZELLO_ISSUER: ${env:ZELLO_ISSUER}
        ZELLO_PRIVATE_KEY: ${env:ZELLO_PRIVATE_KEY}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - s3:GetObject
          Resource: "arn:aws:s3:::${env:OPUS_BUCKET}/*"

functions:
    zelloStream:
        handler: src/handler.zelloStream
        reservedConcurrency: 1 ## no concurrent activity wanted on zello PA
        events: # The Events that trigger this Function
            - s3:
                  bucket: ${env:OPUS_BUCKET}
                  event: s3:ObjectCreated:*
                  rules:
                      - suffix: .opus
                  existing: true # opt
