// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: "us-east-2",
    aws_cognito_identity_pool_id:
        "us-east-2:af0aab6a-d02a-4c24-bfa1-64b10a853afc",
    aws_cognito_region: "us-east-2",
    aws_user_pools_id: "us-east-2_gHYAogcpy",
    aws_user_pools_web_client_id: "755hlhpgiomc38j11um13euoae",
    oauth: {},
};

export default awsmobile;
